development:
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017
  clients:
    default:
      database: mongoid
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        safe: true
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        raise_not_found_error: false
